# Generated by Django 3.1.5 on 2021-08-12 07:57

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', django_jalali.db.models.jDateField(verbose_name='تاریخ رویداد')),
                ('time_left', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='روز باقی مانده(تغییر ندهید)')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('draft', models.BooleanField(default=True, verbose_name='پخش شود؟')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویداد ها',
                'ordering': ('-event_date',),
            },
        ),
    ]
