"""
Django settings for shuut_uni project.
Generated by 'django-admin startproject' using Django 3.1.5.
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

with open("sc.txt", "r") as f:
    SECRET_KEY = f.read()
    f.close()


DEBUG = True

ALLOWED_HOSTS = ["*"]

# HTTPS
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True
# CONN_MAX_AGE = 3600

# # HSTS Settings
# SECURE_HSTS_SECONDS = 3154600
# SECURE_HSTS_PRELOAD = True
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Application definition

INSTALLED_APPS = [
    "baton",
    # ESSENTIALS
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # PACKAGE
    "django_filters",
    "crispy_forms",
    "ckeditor",
    "django_jalali",
    # OWN/CUSTOM APPS
    "news_app.apps.NewsConfig",
    "conference_app.apps.ConferenceAppConfig",
    "event_app.apps.EventAppConfig",
    "general_post_app.apps.GeneralPostAppConfig",
    "lecture_app.apps.LectureAppConfig",
    "pages_app.apps.PagesAppConfig",
    "professor_app.apps.ProfessorAppConfig",
    "faculty_app.apps.FacultyAppConfig",
    "slider_app.apps.SliderAppConfig",
    "sidebar_app.apps.SidebarAppConfig",
    "newsletter.apps.NewsletterConfig",
    "adminpanel.apps.AdminpanelConfig",
    "baton.autodiscover",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "shuut_uni.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "adminpanel" / "templates", BASE_DIR / "news_app" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "pages_app.cp.all_menus",
                "pages_app.cp.all_pages",
                "pages_app.cp.all_sub_menus",
                "faculty_app.cp.list_dp",
                "sidebar_app.cp.list_si",
            ],
        },
    },
]

WSGI_APPLICATION = "shuut_uni.wsgi.application"

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'unidb',
#         'USER': 'unidbadmin',
#         'PASSWORD': 'admin1234',
#         'HOST': 'localhost',
#         'PORT': '',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "app_db.db",
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": ["/var/tmp/django_cache", "c:/Users/ahroo"],
    }
}

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


ALLOW_UNICODE_SLUGS = True


# Maximum size, in bytes, of a request before it will be streamed to the
# file system instead of into memory.
FILE_UPLOAD_MAX_MEMORY_SIZE = 5021440  # i.e. 5 MB

# Maximum size in bytes of request data (excluding file uploads) that will be
# read before a SuspiciousOperation (RequestDataTooBig) is raised.
DATA_UPLOAD_MAX_MEMORY_SIZE = 5021440  # i.e. 5 MB

LANGUAGE_CODE = "fa-IR"
# LANGUAGE_CODE = "en-US"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

VERSION = 1

CRISPY_TEMPLATE_PACK = "bootstrap4"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = (BASE_DIR / "static/",)

LOGIN_REDIRECT_URL = "/admin"
LOGIN_URL = "home_view"
LOGOUT_REDIRECT_URL = "/"


# EMAIL
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp-mail.outlook.com"
EMAIL_HOST_USER = "ahroohi1379@hotmail.com"
EMAIL_PORT = 587
# create a txt file called em where your manage.py file is located
# and put your password in there, don't worry, it will not get uploaded to github
with open("em.txt", "r") as f:
    EMAIL_HOST_PASSWORD = f.read()
    f.close()


# BATON CONFIG
BATON = {
    "SITE_HEADER": "Shhut Uni Admin",
    "SITE_TITLE": "Shhut Uni Admin",
    "INDEX_TITLE": "Shhut Uni Admin",
    "SUPPORT_HREF": "https://github.com/r00terAF18",
    "COPYRIGHT": 'copyright © 2021 <a href="https://gitlab.com/DT.MR">Mostafa Rajabzade</a> and  <a href="https://github.com/r00terAF18">Amir Hossein Roohi</a>',  # noqa
    "POWERED_BY": '<a href="https://gitlab.com/DT.MR">Mostafa Rajabzade</a> and <a href="https://github.com/r00terAF18">Amir Hossein Roohi</a>',
    "CONFIRM_UNSAVED_CHANGES": True,
    "SHOW_MULTIPART_UPLOADING": True,
    "ENABLE_IMAGES_PREVIEW": True,
    "CHANGELIST_FILTERS_IN_MODAL": True,
    "CHANGELIST_FILTERS_ALWAYS_OPEN": False,
    "MENU_ALWAYS_COLLAPSED": False,
    "MENU_TITLE": "Main Menu",
    "GRAVATAR_DEFAULT_IMG": "retro",
}
